blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a question
    url: https://github.com/huhouhua/glctl/discussions/new?category=q-a
    about:  Ask and discuss questions with other glctl community members